services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - vendor_data:/var/www/vendor
    networks:
      - mailcowdockerized_mailcow-network

volumes:
  vendor_data:

networks:
  laravel:
    driver: bridge
  mailcowdockerized_mailcow-network:
    external: true  # Usa la misma red que Nginx Proxy Manager
