version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8000:8000"
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mysql:latest
    environment:
        MYSQL_ROOT_PASSWORD: ejemplo-root-pass
        MYSQL_DATABASE: class_master
        MYSQL_USER: ejemplo-user
        MYSQL_PASSWORD: ejemplo-pass
    ports:
      - "3306:3306"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - db

networks:
  laravel:
    driver: bridge
